[project]
name = "data-mocker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=40.5.1",
    "fastapi>=0.133.0",
    "httpx>=0.28.1",
    "pymongo>=4.16.0",
    "uvicorn[standard]>=0.41.0",
]
